[package]
name = "project_2"
version = "0.1.0"
authors = ["MichaelWang <michael_wangguanyi@163.com>"]
edition = "2018"
build = "hello.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
